### ISSUE TITLE
Error Since Plugin Update

### ISSUE THREAD

**Issue by neverthebride** [ragulka/widget-title-links#3]
Dear Illimar,

After updating your plugin my site no longer works. I receive the following error:

Fatal error: Call to a member function get_settings() on a non-object in /home4/lsb/public_html/NeverTheBride/wp-content/plugins/widget-title-links/widget-title-links.php on line 96

I had no choice but to disable the plugin for now so that the site may work

![image](https://f.cloud.github.com/assets/6302865/1832026/ad108312-73a4-11e3-8c67-161bb638e106.png)

Above is the error screenshot. I hope that you may be able to help.

Best wishes,

Ed

**Comment by ragulka** [comment]
@neverthebride This should be fixed with #4. I will update the plugin in WP plugins repository some time today. After you update, please let me know if it works for you now?

**Comment by neverthebride** [comment]
Many thanks indeed Ragulka, plugin updated and reactivated and problem
fixed on Never The Bride website! If only all plugins had such quick
support!! Thanks again and best wishes, Ed

On Fri, Jan 3, 2014 at 8:11 AM, ragulka notifications@github.com wrote:

> @neverthebride https://github.com/neverthebride This should be fixed
> with #4 https://github.com/ragulka/widget-title-links/pull/4. I will
> update the plugin in WP plugins repository some time today. After you
> update, please let me know if it works for you now?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ragulka/widget-title-links/issues/3#issuecomment-31510002
> .

## 

Never The Bride | neverthebride.com
